### ISSUE TITLE
error in the algorithm

### ISSUE THREAD

**Issue by ArTourter** [cpierquet/wordle#2]
in the english doc, one of the example is `BURGH` with the  code

```
\begin{WordleGrid}{BURGH}
ABATE
HERBS
BURLY
BURGH
\end{WordleGrid}
```
the output highlights the `E` of `HERBS`  (although not the `E` of `ABATE`) when it shouldn't.

if I replace `HERBS` with `CERTS`, both `E` and `T` are highlighted in yellow, same with `CARTS`. it looks like if a letter has already been guessed, it will be highlighted in yellow it is it guessed again, whether it is part of the correct word or not. Case in point, if you repeat `ABATE` all letters are yellow the second time round.

I haven't looked at the code yet so have no suggestions on how to fix it though.

**Comment by cpierquet** [comment]
Seems to be ok now ;-)
![image](https://github.com/cpierquet/wordle/assets/45103962/8f446b1c-0484-46fd-97fc-4368a04d1f41)
