### ISSUE TITLE
Ideas from ttps://tex.stackexchange.com/questions/659860/wordle-like-colored-letter-boxes-in-latex

### ISSUE THREAD

**Issue by AndrewMathas** [cpierquet/wordle#3]
According to your documentation, your package uses "ideas from" a stackexchange post. In practice, you have used the LaTeX3 code from my post without properly acknowledging this.

**Comment by cpierquet** [comment]
Sorry for that :-(
Is it ok for you if I mention better your code and your name in the doc or I should remove the package if you want.
Sorry for this mistake.

**Comment by cpierquet** [comment]
Ok, I'm going to remove my package and make my repo private.
Céd-
